// <auto-generated />
namespace WXQuestionnaire.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addchartlet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchartlet));
        
        string IMigrationMetadata.Id
        {
            get { return "201603050643073_add-chartlet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
